#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAMH.Models
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;
    using System.ComponentModel.DataAnnotations;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webgiay")]
	public partial class GiayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void Insertthuonghieu(thuonghieu instance);
    partial void Updatethuonghieu(thuonghieu instance);
    partial void Deletethuonghieu(thuonghieu instance);
    partial void Insertchitietdonhang(chitietdonhang instance);
    partial void Updatechitietdonhang(chitietdonhang instance);
    partial void Deletechitietdonhang(chitietdonhang instance);
    partial void Insertdondathang(dondathang instance);
    partial void Updatedondathang(dondathang instance);
    partial void Deletedondathang(dondathang instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertloaisanpham(loaisanpham instance);
    partial void Updateloaisanpham(loaisanpham instance);
    partial void Deleteloaisanpham(loaisanpham instance);
    partial void Insertluusp(luusp instance);
    partial void Updateluusp(luusp instance);
    partial void Deleteluusp(luusp instance);
    partial void Insertphanhoi(phanhoi instance);
    partial void Updatephanhoi(phanhoi instance);
    partial void Deletephanhoi(phanhoi instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    #endregion
		
		public GiayDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["webgiayConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GiayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GiayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GiayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GiayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<thuonghieu> thuonghieus
		{
			get
			{
				return this.GetTable<thuonghieu>();
			}
		}
		
		public System.Data.Linq.Table<chitietdonhang> chitietdonhangs
		{
			get
			{
				return this.GetTable<chitietdonhang>();
			}
		}
		
		public System.Data.Linq.Table<dondathang> dondathangs
		{
			get
			{
				return this.GetTable<dondathang>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<loaisanpham> loaisanphams
		{
			get
			{
				return this.GetTable<loaisanpham>();
			}
		}
		
		public System.Data.Linq.Table<luusp> luusps
		{
			get
			{
				return this.GetTable<luusp>();
			}
		}
		
		public System.Data.Linq.Table<phanhoi> phanhois
		{
			get
			{
				return this.GetTable<phanhoi>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserAdmin;
		
		private string _PassAdmin;
		
		private string _Hoten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserAdminChanging(string value);
    partial void OnUserAdminChanged();
    partial void OnPassAdminChanging(string value);
    partial void OnPassAdminChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAdmin", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserAdmin
		{
			get
			{
				return this._UserAdmin;
			}
			set
			{
				if ((this._UserAdmin != value))
				{
					this.OnUserAdminChanging(value);
					this.SendPropertyChanging();
					this._UserAdmin = value;
					this.SendPropertyChanged("UserAdmin");
					this.OnUserAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassAdmin", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PassAdmin
		{
			get
			{
				return this._PassAdmin;
			}
			set
			{
				if ((this._PassAdmin != value))
				{
					this.OnPassAdminChanging(value);
					this.SendPropertyChanging();
					this._PassAdmin = value;
					this.SendPropertyChanged("PassAdmin");
					this.OnPassAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thuonghieu")]
	public partial class thuonghieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mathuonghieu;
		
		private string _tenthuonghieu;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmathuonghieuChanging(int value);
    partial void OnmathuonghieuChanged();
    partial void OntenthuonghieuChanging(string value);
    partial void OntenthuonghieuChanged();
    #endregion
		
		public thuonghieu()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mathuonghieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mathuonghieu
		{
			get
			{
				return this._mathuonghieu;
			}
			set
			{
				if ((this._mathuonghieu != value))
				{
					this.OnmathuonghieuChanging(value);
					this.SendPropertyChanging();
					this._mathuonghieu = value;
					this.SendPropertyChanged("mathuonghieu");
					this.OnmathuonghieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenthuonghieu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenthuonghieu
		{
			get
			{
				return this._tenthuonghieu;
			}
			set
			{
				if ((this._tenthuonghieu != value))
				{
					this.OntenthuonghieuChanging(value);
					this.SendPropertyChanging();
					this._tenthuonghieu = value;
					this.SendPropertyChanged("tenthuonghieu");
					this.OntenthuonghieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="thuonghieu_sanpham", Storage="_sanphams", ThisKey="mathuonghieu", OtherKey="mathuonghieu")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.thuonghieu = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.thuonghieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietdonhang")]
	public partial class chitietdonhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _madh;
		
		private string _masp;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<double> _dongia;
		
		private EntityRef<dondathang> _dondathang;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadhChanging(int value);
    partial void OnmadhChanged();
    partial void OnmaspChanging(string value);
    partial void OnmaspChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OndongiaChanging(System.Nullable<double> value);
    partial void OndongiaChanged();
    #endregion
		
		public chitietdonhang()
		{
			this._dondathang = default(EntityRef<dondathang>);
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int madh
		{
			get
			{
				return this._madh;
			}
			set
			{
				if ((this._madh != value))
				{
					if (this._dondathang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadhChanging(value);
					this.SendPropertyChanging();
					this._madh = value;
					this.SendPropertyChanged("madh");
					this.OnmadhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="Float")]
		public System.Nullable<double> dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this.OndongiaChanging(value);
					this.SendPropertyChanging();
					this._dongia = value;
					this.SendPropertyChanged("dongia");
					this.OndongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dondathang_chitietdonhang", Storage="_dondathang", ThisKey="madh", OtherKey="madh", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public dondathang dondathang
		{
			get
			{
				return this._dondathang.Entity;
			}
			set
			{
				dondathang previousValue = this._dondathang.Entity;
				if (((previousValue != value) 
							|| (this._dondathang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dondathang.Entity = null;
						previousValue.chitietdonhangs.Remove(this);
					}
					this._dondathang.Entity = value;
					if ((value != null))
					{
						value.chitietdonhangs.Add(this);
						this._madh = value.madh;
					}
					else
					{
						this._madh = default(int);
					}
					this.SendPropertyChanged("dondathang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_chitietdonhang", Storage="_sanpham", ThisKey="masp", OtherKey="masp", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.chitietdonhangs.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.chitietdonhangs.Add(this);
						this._masp = value.masp;
					}
					else
					{
						this._masp = default(string);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dondathang")]
	public partial class dondathang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _madh;
		
		private string _dathanhtoan;
		
		private System.Nullable<System.DateTime> _ngaydat;
		
		private string _noigiao;
		
		private System.Nullable<int> _makh;
		
		private System.Nullable<bool> _tinhtranggiaohang;
		
		private System.Nullable<decimal> _thanhtien;
		
		private EntitySet<chitietdonhang> _chitietdonhangs;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadhChanging(int value);
    partial void OnmadhChanged();
    partial void OndathanhtoanChanging(string value);
    partial void OndathanhtoanChanged();
    partial void OnngaydatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydatChanged();
    partial void OnnoigiaoChanging(string value);
    partial void OnnoigiaoChanged();
    partial void OnmakhChanging(System.Nullable<int> value);
    partial void OnmakhChanged();
    partial void OntinhtranggiaohangChanging(System.Nullable<bool> value);
    partial void OntinhtranggiaohangChanged();
    partial void OnthanhtienChanging(System.Nullable<decimal> value);
    partial void OnthanhtienChanged();
    #endregion
		
		public dondathang()
		{
			this._chitietdonhangs = new EntitySet<chitietdonhang>(new Action<chitietdonhang>(this.attach_chitietdonhangs), new Action<chitietdonhang>(this.detach_chitietdonhangs));
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int madh
		{
			get
			{
				return this._madh;
			}
			set
			{
				if ((this._madh != value))
				{
					this.OnmadhChanging(value);
					this.SendPropertyChanging();
					this._madh = value;
					this.SendPropertyChanged("madh");
					this.OnmadhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dathanhtoan", DbType="NChar(10)")]
		public string dathanhtoan
		{
			get
			{
				return this._dathanhtoan;
			}
			set
			{
				if ((this._dathanhtoan != value))
				{
					this.OndathanhtoanChanging(value);
					this.SendPropertyChanging();
					this._dathanhtoan = value;
					this.SendPropertyChanged("dathanhtoan");
					this.OndathanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydat", DbType="Date")]
		public System.Nullable<System.DateTime> ngaydat
		{
			get
			{
				return this._ngaydat;
			}
			set
			{
				if ((this._ngaydat != value))
				{
					this.OnngaydatChanging(value);
					this.SendPropertyChanging();
					this._ngaydat = value;
					this.SendPropertyChanged("ngaydat");
					this.OnngaydatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noigiao", DbType="NVarChar(50)")]
		public string noigiao
		{
			get
			{
				return this._noigiao;
			}
			set
			{
				if ((this._noigiao != value))
				{
					this.OnnoigiaoChanging(value);
					this.SendPropertyChanging();
					this._noigiao = value;
					this.SendPropertyChanged("noigiao");
					this.OnnoigiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="Int")]
		public System.Nullable<int> makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtranggiaohang", DbType="Bit")]
		public System.Nullable<bool> tinhtranggiaohang
		{
			get
			{
				return this._tinhtranggiaohang;
			}
			set
			{
				if ((this._tinhtranggiaohang != value))
				{
					this.OntinhtranggiaohangChanging(value);
					this.SendPropertyChanging();
					this._tinhtranggiaohang = value;
					this.SendPropertyChanged("tinhtranggiaohang");
					this.OntinhtranggiaohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Money")]
		public System.Nullable<decimal> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this.OnthanhtienChanging(value);
					this.SendPropertyChanging();
					this._thanhtien = value;
					this.SendPropertyChanged("thanhtien");
					this.OnthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dondathang_chitietdonhang", Storage="_chitietdonhangs", ThisKey="madh", OtherKey="madh")]
		public EntitySet<chitietdonhang> chitietdonhangs
		{
			get
			{
				return this._chitietdonhangs;
			}
			set
			{
				this._chitietdonhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_dondathang", Storage="_khachhang", ThisKey="makh", OtherKey="makh", IsForeignKey=true, DeleteRule="CASCADE")]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.dondathangs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.dondathangs.Add(this);
						this._makh = value.makh;
					}
					else
					{
						this._makh = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.dondathang = this;
		}
		
		private void detach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.dondathang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _makh;
		
		private string _tenkh;
		
		private string _sdtkh;
		
		private string _emailkh;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _diachikh;
		
		private string _tentkkh;
		
		private string _matkhaukh;
		
		private EntitySet<dondathang> _dondathangs;
		
		private EntitySet<luusp> _luusps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhChanging(int value);
    partial void OnmakhChanged();
    partial void OntenkhChanging(string value);
    partial void OntenkhChanged();
    partial void OnsdtkhChanging(string value);
    partial void OnsdtkhChanged();
    partial void OnemailkhChanging(string value);
    partial void OnemailkhChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OndiachikhChanging(string value);
    partial void OndiachikhChanged();
    partial void OntentkkhChanging(string value);
    partial void OntentkkhChanged();
    partial void OnmatkhaukhChanging(string value);
    partial void OnmatkhaukhChanged();
    #endregion
		
		public khachhang()
		{
			this._dondathangs = new EntitySet<dondathang>(new Action<dondathang>(this.attach_dondathangs), new Action<dondathang>(this.detach_dondathangs));
			this._luusps = new EntitySet<luusp>(new Action<luusp>(this.attach_luusps), new Action<luusp>(this.detach_luusps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
        [Required(ErrorMessage = "Chưa nhập họ tên")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkh", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenkh
		{
			get
			{
				return this._tenkh;
			}
			set
			{
				if ((this._tenkh != value))
				{
					this.OntenkhChanging(value);
					this.SendPropertyChanging();
					this._tenkh = value;
					this.SendPropertyChanged("tenkh");
					this.OntenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtkh", DbType="NVarChar(11)")]
		public string sdtkh
		{
			get
			{
				return this._sdtkh;
			}
			set
			{
				if ((this._sdtkh != value))
				{
					this.OnsdtkhChanging(value);
					this.SendPropertyChanging();
					this._sdtkh = value;
					this.SendPropertyChanged("sdtkh");
					this.OnsdtkhChanged();
				}
			}
		}
        [Required(ErrorMessage = "Chưa nhập email")]
        [EmailAddress(ErrorMessage = "Địa chỉ email phải có dạng abc@gmail.com")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailkh", DbType="VarChar(50)")]
		public string emailkh
		{
			get
			{
				return this._emailkh;
			}
			set
			{
				if ((this._emailkh != value))
				{
					this.OnemailkhChanging(value);
					this.SendPropertyChanging();
					this._emailkh = value;
					this.SendPropertyChanged("emailkh");
					this.OnemailkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachikh", DbType="NVarChar(100)")]
		public string diachikh
		{
			get
			{
				return this._diachikh;
			}
			set
			{
				if ((this._diachikh != value))
				{
					this.OndiachikhChanging(value);
					this.SendPropertyChanging();
					this._diachikh = value;
					this.SendPropertyChanged("diachikh");
					this.OndiachikhChanged();
				}
			}
		}
        [Required(ErrorMessage = "Chưa nhập tên tài khoản")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentkkh", DbType="VarChar(100)")]
		public string tentkkh
		{
			get
			{
				return this._tentkkh;
			}
			set
			{
				if ((this._tentkkh != value))
				{
					this.OntentkkhChanging(value);
					this.SendPropertyChanging();
					this._tentkkh = value;
					this.SendPropertyChanged("tentkkh");
					this.OntentkkhChanged();
				}
			}
		}
        [Required(ErrorMessage = "Chưa nhập lại mật khẩu")]
        public string matkhau { get; set; }

        [Required(ErrorMessage = "Chưa nhập lại mật khẩu")]
        [Compare("matkhau", ErrorMessage = "Mật khẩu ko trùng khớp")]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhaukh", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string matkhaukh
		{
			get
			{
				return this._matkhaukh;
			}
			set
			{
				if ((this._matkhaukh != value))
				{
					this.OnmatkhaukhChanging(value);
					this.SendPropertyChanging();
					this._matkhaukh = value;
					this.SendPropertyChanged("matkhaukh");
					this.OnmatkhaukhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_dondathang", Storage="_dondathangs", ThisKey="makh", OtherKey="makh")]
		public EntitySet<dondathang> dondathangs
		{
			get
			{
				return this._dondathangs;
			}
			set
			{
				this._dondathangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_luusp", Storage="_luusps", ThisKey="makh", OtherKey="makh")]
		public EntitySet<luusp> luusps
		{
			get
			{
				return this._luusps;
			}
			set
			{
				this._luusps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dondathangs(dondathang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_dondathangs(dondathang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
		
		private void attach_luusps(luusp entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_luusps(luusp entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaisanpham")]
	public partial class loaisanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maloaisp;
		
		private string _tenloaisp;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaispChanging(int value);
    partial void OnmaloaispChanged();
    partial void OntenloaispChanging(string value);
    partial void OntenloaispChanged();
    #endregion
		
		public loaisanpham()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaisp", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maloaisp
		{
			get
			{
				return this._maloaisp;
			}
			set
			{
				if ((this._maloaisp != value))
				{
					this.OnmaloaispChanging(value);
					this.SendPropertyChanging();
					this._maloaisp = value;
					this.SendPropertyChanged("maloaisp");
					this.OnmaloaispChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloaisp", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenloaisp
		{
			get
			{
				return this._tenloaisp;
			}
			set
			{
				if ((this._tenloaisp != value))
				{
					this.OntenloaispChanging(value);
					this.SendPropertyChanging();
					this._tenloaisp = value;
					this.SendPropertyChanged("tenloaisp");
					this.OntenloaispChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaisanpham_sanpham", Storage="_sanphams", ThisKey="maloaisp", OtherKey="maloaisp")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.loaisanpham = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.loaisanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.luusp")]
	public partial class luusp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _makh;
		
		private string _masp;
		
		private EntityRef<khachhang> _khachhang;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmakhChanging(System.Nullable<int> value);
    partial void OnmakhChanged();
    partial void OnmaspChanging(string value);
    partial void OnmaspChanged();
    #endregion
		
		public luusp()
		{
			this._khachhang = default(EntityRef<khachhang>);
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="Int")]
		public System.Nullable<int> makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="NVarChar(50)")]
		public string masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_luusp", Storage="_khachhang", ThisKey="makh", OtherKey="makh", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.luusps.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.luusps.Add(this);
						this._makh = value.makh;
					}
					else
					{
						this._makh = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_luusp", Storage="_sanpham", ThisKey="masp", OtherKey="masp", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.luusps.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.luusps.Add(this);
						this._masp = value.masp;
					}
					else
					{
						this._masp = default(string);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phanhoi")]
	public partial class phanhoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _hoten;
		
		private string _noidungmail;
		
		private string _mail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnnoidungmailChanging(string value);
    partial void OnnoidungmailChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    #endregion
		
		public phanhoi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidungmail", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string noidungmail
		{
			get
			{
				return this._noidungmail;
			}
			set
			{
				if ((this._noidungmail != value))
				{
					this.OnnoidungmailChanging(value);
					this.SendPropertyChanging();
					this._noidungmail = value;
					this.SendPropertyChanged("noidungmail");
					this.OnnoidungmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanpham")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _masp;
		
		private string _tensp;
		
		private System.Nullable<int> _maloaisp;
		
		private System.Nullable<decimal> _dongia;
		
		private System.Nullable<System.DateTime> _ngaynhap;
		
		private System.Nullable<System.DateTime> _ngayxuat;
		
		private System.Nullable<int> _soluongdaban;
		
		private string _doanmota;
		
		private string _motachitiet;
		
		private System.Nullable<int> _mathuonghieu;
		
		private System.Nullable<int> _masize;
		
		private string _hinhsp;
		
		private EntitySet<chitietdonhang> _chitietdonhangs;
		
		private EntitySet<luusp> _luusps;
		
		private EntityRef<loaisanpham> _loaisanpham;
		
		private EntityRef<thuonghieu> _thuonghieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaspChanging(string value);
    partial void OnmaspChanged();
    partial void OntenspChanging(string value);
    partial void OntenspChanged();
    partial void OnmaloaispChanging(System.Nullable<int> value);
    partial void OnmaloaispChanged();
    partial void OndongiaChanging(System.Nullable<decimal> value);
    partial void OndongiaChanged();
    partial void OnngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaynhapChanged();
    partial void OnngayxuatChanging(System.Nullable<System.DateTime> value);
    partial void OnngayxuatChanged();
    partial void OnsoluongdabanChanging(System.Nullable<int> value);
    partial void OnsoluongdabanChanged();
    partial void OndoanmotaChanging(string value);
    partial void OndoanmotaChanged();
    partial void OnmotachitietChanging(string value);
    partial void OnmotachitietChanged();
    partial void OnmathuonghieuChanging(System.Nullable<int> value);
    partial void OnmathuonghieuChanged();
    partial void OnmasizeChanging(System.Nullable<int> value);
    partial void OnmasizeChanged();
    partial void OnhinhspChanging(string value);
    partial void OnhinhspChanged();
    #endregion
		
		public sanpham()
		{
			this._chitietdonhangs = new EntitySet<chitietdonhang>(new Action<chitietdonhang>(this.attach_chitietdonhangs), new Action<chitietdonhang>(this.detach_chitietdonhangs));
			this._luusps = new EntitySet<luusp>(new Action<luusp>(this.attach_luusps), new Action<luusp>(this.detach_luusps));
			this._loaisanpham = default(EntityRef<loaisanpham>);
			this._thuonghieu = default(EntityRef<thuonghieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensp", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tensp
		{
			get
			{
				return this._tensp;
			}
			set
			{
				if ((this._tensp != value))
				{
					this.OntenspChanging(value);
					this.SendPropertyChanging();
					this._tensp = value;
					this.SendPropertyChanged("tensp");
					this.OntenspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaisp", DbType="Int")]
		public System.Nullable<int> maloaisp
		{
			get
			{
				return this._maloaisp;
			}
			set
			{
				if ((this._maloaisp != value))
				{
					if (this._loaisanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaispChanging(value);
					this.SendPropertyChanging();
					this._maloaisp = value;
					this.SendPropertyChanged("maloaisp");
					this.OnmaloaispChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="Money")]
		public System.Nullable<decimal> dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this.OndongiaChanging(value);
					this.SendPropertyChanging();
					this._dongia = value;
					this.SendPropertyChanged("dongia");
					this.OndongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="Date")]
		public System.Nullable<System.DateTime> ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayxuat", DbType="Date")]
		public System.Nullable<System.DateTime> ngayxuat
		{
			get
			{
				return this._ngayxuat;
			}
			set
			{
				if ((this._ngayxuat != value))
				{
					this.OnngayxuatChanging(value);
					this.SendPropertyChanging();
					this._ngayxuat = value;
					this.SendPropertyChanged("ngayxuat");
					this.OnngayxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongdaban", DbType="Int")]
		public System.Nullable<int> soluongdaban
		{
			get
			{
				return this._soluongdaban;
			}
			set
			{
				if ((this._soluongdaban != value))
				{
					this.OnsoluongdabanChanging(value);
					this.SendPropertyChanging();
					this._soluongdaban = value;
					this.SendPropertyChanged("soluongdaban");
					this.OnsoluongdabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanmota", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string doanmota
		{
			get
			{
				return this._doanmota;
			}
			set
			{
				if ((this._doanmota != value))
				{
					this.OndoanmotaChanging(value);
					this.SendPropertyChanging();
					this._doanmota = value;
					this.SendPropertyChanged("doanmota");
					this.OndoanmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motachitiet", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string motachitiet
		{
			get
			{
				return this._motachitiet;
			}
			set
			{
				if ((this._motachitiet != value))
				{
					this.OnmotachitietChanging(value);
					this.SendPropertyChanging();
					this._motachitiet = value;
					this.SendPropertyChanged("motachitiet");
					this.OnmotachitietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mathuonghieu", DbType="Int")]
		public System.Nullable<int> mathuonghieu
		{
			get
			{
				return this._mathuonghieu;
			}
			set
			{
				if ((this._mathuonghieu != value))
				{
					if (this._thuonghieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmathuonghieuChanging(value);
					this.SendPropertyChanging();
					this._mathuonghieu = value;
					this.SendPropertyChanged("mathuonghieu");
					this.OnmathuonghieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masize", DbType="Int")]
		public System.Nullable<int> masize
		{
			get
			{
				return this._masize;
			}
			set
			{
				if ((this._masize != value))
				{
					this.OnmasizeChanging(value);
					this.SendPropertyChanging();
					this._masize = value;
					this.SendPropertyChanged("masize");
					this.OnmasizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhsp", DbType="NVarChar(50)")]
		public string hinhsp
		{
			get
			{
				return this._hinhsp;
			}
			set
			{
				if ((this._hinhsp != value))
				{
					this.OnhinhspChanging(value);
					this.SendPropertyChanging();
					this._hinhsp = value;
					this.SendPropertyChanged("hinhsp");
					this.OnhinhspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_chitietdonhang", Storage="_chitietdonhangs", ThisKey="masp", OtherKey="masp")]
		public EntitySet<chitietdonhang> chitietdonhangs
		{
			get
			{
				return this._chitietdonhangs;
			}
			set
			{
				this._chitietdonhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_luusp", Storage="_luusps", ThisKey="masp", OtherKey="masp")]
		public EntitySet<luusp> luusps
		{
			get
			{
				return this._luusps;
			}
			set
			{
				this._luusps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaisanpham_sanpham", Storage="_loaisanpham", ThisKey="maloaisp", OtherKey="maloaisp", IsForeignKey=true, DeleteRule="CASCADE")]
		public loaisanpham loaisanpham
		{
			get
			{
				return this._loaisanpham.Entity;
			}
			set
			{
				loaisanpham previousValue = this._loaisanpham.Entity;
				if (((previousValue != value) 
							|| (this._loaisanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaisanpham.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._loaisanpham.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._maloaisp = value.maloaisp;
					}
					else
					{
						this._maloaisp = default(Nullable<int>);
					}
					this.SendPropertyChanged("loaisanpham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="thuonghieu_sanpham", Storage="_thuonghieu", ThisKey="mathuonghieu", OtherKey="mathuonghieu", IsForeignKey=true)]
		public thuonghieu thuonghieu
		{
			get
			{
				return this._thuonghieu.Entity;
			}
			set
			{
				thuonghieu previousValue = this._thuonghieu.Entity;
				if (((previousValue != value) 
							|| (this._thuonghieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._thuonghieu.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._thuonghieu.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._mathuonghieu = value.mathuonghieu;
					}
					else
					{
						this._mathuonghieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("thuonghieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
		
		private void attach_luusps(luusp entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_luusps(luusp entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
	}
}
#pragma warning restore 1591
